Some refactor + normal user / root differences

diff --git a/rbashup b/rbashup
--- a/rbashup
+++ b/rbashup
@@ -3,7 +3,7 @@
 #
 #   rbashup - rsync bash backup
 #
-    version=0.0.1
+    version=0.0.2
 #
 #   Author:      Toni Homedes i Saun
 #   Copyright:   2013 Toni Homedes i Saun
@@ -27,58 +27,55 @@
 #   v0.0.1 => The purging algorithm in v0.0.0 was plain wrong. I'm rewriting
 #   it with a new idea, the "bucket filter" => done, not very happy about the
 #   result, it works well but code should be cleaner
-#   
+#
+#   v0.0.2 => Fixed default values for normal user / super user (root).
+#   Some refactoring.
+#
+#   TODO:
+#
+#       - Trap unexpected exit and cleanup()
+#
+#       - Improve purging algorithm. Still not very happy about it.
+#
+#       - Find someone who can test it on non Linux systems: Mac, BSD, AIX,
+#         HP-UX, ...
+#
 ##############################################################################
 
 #-----------------------------------------------------------------------------
 log() {
     local priority="$1" format="$2"; shift 2
     local now=$(date --rfc-3339=seconds)
-    local msg="$(printf "%s %s: $format\n" "$now" "$priority" "$@")"
+    local msg="$(printf "%s %s: $format" "$now" "$priority" "$@")"
 
     if [[ -x ${opts[logger]} ]]; then
-	${opts[logger]} \
-	    -p "${opts[logger-facility]}.$priority" \
-	    -t rbashup "$msg"
+        ${opts[logger]} \
+            -p "${opts[logger-facility]}.$priority" \
+            -t rbashup "$msg"
     else if [[ -n ${opts[log-file]} ]]; then
-	echo "$msg" >> "${opts[log-file]}"
+        echo "$msg" >> "${opts[log-file]}"
     else
-	case "$priority" in
-	    WARNING|ERROR)  echo "$msg" >&2 ;;
-	    *)              echo "$msg"     ;;
-	esac
+        case "$priority" in
+            WARNING|ERROR)  echo "$msg" >&2 ;;
+            *)              echo "$msg"     ;;
+        esac
     fi fi
 }
 
 #-----------------------------------------------------------------------------
-ERROR() {
-    log ERROR "$@"
-    kill -s TERM $TOP_PID
-}
+ERROR()   { log ERROR "$@"; kill -s TERM $TOP_PID ;}
+WARNING() { log WARNING "$@"                      ;}
+NOTICE()  { log NOTICE "$@"                       ;}
+INFO()    { ((opt_v > 0)) && log INFO "$@"        ;}
+DEBUG()   { ((opt_v > 1)) && log DEBUG "$@"       ;}
 
 #-----------------------------------------------------------------------------
-WARNING() {
-    log WARNING "$@"
-}
+check_input_file() {
+    (( $# == 2 )) || ERROR "Invalid call to %s()" "$FUNCNAME"
+    local desc="$1"
+    local file="$2"
 
-#-----------------------------------------------------------------------------
-NOTICE() {
-    log NOTICE "$@"
-}
-
-#-----------------------------------------------------------------------------
-INFO() {
-    ((opt_v > 0)) && log INFO "$@"
-}
-
-#-----------------------------------------------------------------------------
-DEBUG() {
-    ((opt_v > 1)) && log DEBUG "$@"
-}
-
-#-----------------------------------------------------------------------------
-version() {
-    echo $version
+    [[ -r "$file" ]] || ERROR "Non readable %s: \"%s\"" "$desc" "$file"
 }
 
 #-----------------------------------------------------------------------------
@@ -89,18 +86,18 @@ Usage:
     rbashup [options] backup-set
 
     where options are:
-	-V|--version        show version number and exit
-	-c|--config file    use given config file
-	-h|--help           show this message and exit
-	-n                  Dry Run, don't actually do nothing
-	-v                  verbose, use 1 or more times
+        -V|--version        show version number and exit
+        -c|--config file    use given config file
+        -h|--help           show this message and exit
+        -n                  Dry Run, don't actually do nothing
+        -v                  verbose, use 1 or more times
 EOF
 
     if [[ $# > 0 ]]; then
-	local fmt="$1"; shift
-	ERROR "$fmt\n\n%s" "$@" "$s"
+        local fmt="$1"; shift
+        ERROR "$fmt\n\n%s" "$@" "$s"
     else
-	echo "$s"
+        echo "$s"
     fi
 }
 
@@ -124,26 +121,24 @@ version_cmp() {
 
     while true; do
 
-	fa="${a%%.*}"
-	fb="${b%%.*}"
+        fa="${a%%.*}"
+        fb="${b%%.*}"
 
-	((fa != fb)) && break
+        ((fa != fb)) && break
 
-	a="${a#$fa}"; a="${a#.}"
-	b="${b#$fb}"; b="${b#.}"
+        a="${a#$fa}"; a="${a#.}"
+        b="${b#$fb}"; b="${b#.}"
 
-	if [[ -z $a && -z $b ]]; then
-	    echo 0
-	    return
-	fi
+        if [[ -z $a && -z $b ]]; then
+            echo 0
+            return
+        fi
     done
     ((fa > fb)) && echo 1 || echo -1
 }
 
 #-----------------------------------------------------------------------------
-rsync_version() {
-    rsync --version | awk 'NR==1 { print $3 }'
-}
+rsync_version() { rsync --version | awk 'NR==1 { print $3 }' ;}
 
 #-----------------------------------------------------------------------------
 #
@@ -154,9 +149,7 @@ rsync_version() {
 #   @return UNIX epoch seconds for date
 #
 #-----------------------------------------------------------------------------
-epoch() {
-    date -d "${1:0:10} ${1:11:2}:${1:13}" +%s
-}
+epoch() { date -d "${1:0:10} ${1:11:2}:${1:13}" +%s ;}
 
 #-----------------------------------------------------------------------------
 #
@@ -168,47 +161,50 @@ epoch() {
 #
 #-----------------------------------------------------------------------------
 ini_read_section() {
-    [[ $# -eq 3   ]] || ERROR "Invalid call to ini_read_section"
+    (( $# == 3 )) || ERROR "Invalid call to %s()" "$FUNCNAME"
 
     local array="$1" file="$2" section="$3"
     local l k v
 
-    [[ -r "$file" ]] || ERROR "Can't read from \"%s\"" "$file"
+    check_input_file config "$file"
 
     #DEBUG "ini_read_section $array $file $section"
 
     for l in $(sed -n '/^[ \t]*\['"$section"'\]/,/\[/s/^[ \t]*\([^#; \t][^ \t=]*\).*=[ \t]*\(.*\)/\1=\2/p' $file)
     do
-	k=${l%%=*}
-	v=${l#*=}
-	eval $array[$k]="$v"
+        k=${l%%=*}
+        v=${l#*=}
+        eval $array[$k]="$v"
     done
 }
 
 #-----------------------------------------------------------------------------
 config_dump() {
     local k kk
-    echo
     echo Config:
-    echo
     for k in "${!opts[@]}"; do echo "$k"; done | sort | while read kk; do
-	printf "%-20s ==> %s\n" "$kk" "${opts[$kk]}"; 
+        printf "%-20s ==> %s\n" "$kk" "${opts[$kk]}";
     done
-    echo
 }
 
 #-----------------------------------------------------------------------------
 backup() {
+    (( $# == 4 )) || ERROR "Invalid call to %s()" "$FUNCNAME"
+
     local src="$1" dstbase="$2" now="$3" excludes="$4"
     shift 4
 
+    DEBUG 'backup "%s" "%s" "%s" "%s"' "$src" "$dstbase" "$now" "$excludes"
+
     local \
-	dstfull="$dstbase/$now" \
-	latest="$dstbase/latest" \
-	tmp="$dstbase/.in-progress"
+        dstfull="$dstbase/$now" \
+        latest="$dstbase/latest" \
+        tmp="$dstbase/.in-progress"
+
+    [[ -z $opt_n ]] && mkdir -p "$dstbase"
 
     if [[ -n $excludes ]]; then
-	excludes=$(echo ",$excludes" | sed 's/[,]/ --exclude-from=/g')
+        excludes=$(echo ",$excludes" | sed 's/[,]/ --exclude-from=/g')
     fi
 
     NOTICE "Backup \"$src\""
@@ -217,107 +213,136 @@ backup() {
     [[ -d "$dstfull" ]] && ERROR "Wait a minute!"
 
     if [[ -d "$latest" ]]; then
-	local link="--link-dest=$latest/"
+        local link="--link-dest=$latest/"
     else
-	local link=
+        local link=
     fi
 
     [[ -z $opt_n ]] && rm -rf "$tmp" # just in case there was something left
-    
+
     rsync $opt_n -a $excludes "$@" $link "$src/" "$tmp/" \
-	&& [[ -z $opt_n ]] \
-	&& mv "$tmp" "$dstfull" \
-	&& [[ -d "$latest" ]] && rm "$latest"
+        && [[ -z $opt_n ]] \
+        && mv "$tmp" "$dstfull" \
+        && [[ -d "$latest" ]] && rm "$latest"
     [[ ! -d "$latest" && -d "$dstfull" ]] && ln -s "$now" "$latest"
 }
 
 #-----------------------------------------------------------------------------
 purge() {
+    (( $# == 2 )) || ERROR "Invalid call to %s()" "$FUNCNAME"
+
     local path="$1"
     local x y list
-    local -i i j now=$(epoch "$2")
+    local -i e i j now=$(epoch "$2")
     local -A backups
 
     NOTICE "Purging old backups..."
-    INFO "Now is $2 ($now)"
 
     ((now = now + 0 * 3600))
 
     # load an array with all existing backups
-    list="$(find "$path" -mindepth 1 -maxdepth 1 -type d -name "$mask" | 
+    list="$(find "$path" -mindepth 1 -maxdepth 1 -type d -name "$mask" |
             sort -r)"
 
-    while read x; do backups["$x"]=0; done < <(echo "$list")
-
-    #for x in "${!backups[@]}"; do echo "x = $x"; done
+    while read x; do backups["$x"]=0; DEBUG "%s" "$x"; done < <(echo "$list")
 
     # Mark first "keep-last" for keeping
     ((i = 0))
-    while read x && ((i++ < ${opts[keep-last]})); do 
-	backups["$x"]=1;
+    while read x && ((i++ < ${opts[keep-last]})); do
+        backups["$x"]=1;
     done < <(echo "$list")
 
     # Mark hourly
     periods=${opts[keep-hourly]}
     ((last_period = periods))
     while read x; do
-	e=$(epoch $(basename "$x"))
-	((period = (now - e) / 3600))
-	if ((period < last_period)); then
-	    ((last_period = period))
-	    backups["$x"]=1;
-	fi
+        e=$(epoch $(basename "$x"))
+        ((period = (now - e) / 3600))
+        if ((period < last_period)); then
+            ((last_period = period))
+            backups["$x"]=1;
+        fi
     done < <(echo "$list" | sort) # run from past to present
 
     # Mark daily
     periods=${opts[keep-daily]}
     ((last_period = periods))
     while read x; do
-	e=$(epoch $(basename "$x"))
-	((period = (now - e) / 86400))
-	if ((period < last_period)); then
-	    ((last_period = period))
-	    backups["$x"]=1;
-	fi
+        e=$(epoch $(basename "$x"))
+        ((period = (now - e) / 86400))
+        if ((period < last_period)); then
+            ((last_period = period))
+            backups["$x"]=1;
+        fi
     done < <(echo "$list" | sort) # run from past to present
 
     # Mark weekly
     periods=${opts[keep-weekly]}
     ((last_period = periods))
     while read x; do
-	e=$(epoch $(basename "$x"))
-	((period = (now - e) / (7 * 86400) ))
-	if ((period < last_period)); then
-	    ((last_period = period))
-	    backups["$x"]=1;
-	fi
+        e=$(epoch $(basename "$x"))
+        ((period = (now - e) / (7 * 86400) ))
+        if ((period < last_period)); then
+            ((last_period = period))
+            backups["$x"]=1;
+        fi
     done < <(echo "$list" | sort) # run from past to present
 
     # Mark monthly
     periods=${opts[keep-monthly]}
     ((last_period = periods))
     while read x; do
-	e=$(epoch $(basename "$x"))
-	((period = (now - e) / (30 * 86400) ))
-	if ((period < last_period)); then
-	    ((last_period = period))
-	    backups["$x"]=1;
-	fi
+        e=$(epoch $(basename "$x"))
+        ((period = (now - e) / (30 * 86400) ))
+        if ((period < last_period)); then
+            ((last_period = period))
+            backups["$x"]=1;
+        fi
     done < <(echo "$list" | sort) # run from past to present
 
-    while read x; do 
-	#echo "$x => ${backups["$x"]}"; 
-	if ((${backups["$x"]})); then
-	    INFO "Keeping  \"$x\""
-	else
-	    NOTICE "Removing \"$x\""
-	    [[ -z $opt_n ]] && rm -rf "$x"
-	    true
-	fi
+    # Do the actual keeping or removing
+    while read x; do
+        #echo "$x => ${backups["$x"]}";
+        if ((${backups["$x"]})); then
+            INFO "Keeping  \"$x\""
+        else
+            NOTICE "Removing \"$x\""
+            [[ -z $opt_n ]] && rm -rf "$x"
+            true
+        fi
     done < <(echo "$list")
 }
 
-###########################################################################
+#-----------------------------------------------------------------------------
+load_config() {
+    # Set default options
+
+    if ((EUID == 0)); then  # super user ?
+        opts[log-file]=/var/log/rbashup.log
+        opts[lock-file]=/var/run/rbashup.pid
+    else
+        opts[log-file]=
+        opts[lock-file]=/tmp/rbashup.pid
+    fi
+
+    check_input_file "config file" "$opt_config"
+
+    ini_read_section opts "$opt_config"  global
+    ini_read_section opts "$opt_config" "$opt_set"
+
+    echo "${opts[excludes]}" | tr , "\n" |
+        while read f; do
+            [[ -n "$f" ]] && check_input_file excludes "$f"
+        done
+
+    DEBUG %s "$(config_dump)"
+}
+
+###############################################################################
+##
+##   M A I N
+##
+###############################################################################
 
 # If you change date_format you have to change epoch() and $mask
 # accordingly.
@@ -343,39 +368,39 @@ fi
 if [[ $(version_cmp $(rsync_version) 2.5.7) -lt 0 ]]; then
     ERROR "Invalid version of rsync. 2.5.7 or more required"
 fi
+
+#trap 'ERROR "Error in line %s" "${LINENO}"' ERR
+
 #
 #   Parse options
 #
-opt_n=
-opt_v=0
+opt_n=                  # dry run
+opt_v=0                 # verbosity level
+# configuration file: try ~/.rbashup and, if not, /etc/rbashup.cfg
 opt_config=~/.rbashup
 [[ -f $opt_config ]] || opt_config=/etc/rbashup.cfg
 
-eval set -- $(getopt -n $(basename "$0") -o f:hnVv \
+eval set -- $(getopt -n $(basename "$0") -o c:hnVv \
     -l config,help,version -- "$@")
 
 while true; do
     case "$1" in
-	-V|--version)   version; exit 0;;
-	-c|--config)    opt_config="$2"; shift;;
-	-h|--help)      usage; exit 0;;
-	-n)             opt_n="-n";;
-	-v)             ((++opt_v));;
-	--)	        shift; break;;
-	*)              ERROR "Undefined parameter '%s'" "$1"
+        -V|--version)   echo "$version"; exit 0;;
+        -c|--config)    opt_config="$2"; shift;;
+        -h|--help)      usage; exit 0;;
+        -n)             opt_n="-n";;
+        -v)             ((++opt_v));;
+        --)             shift; break;;
+        *)              ERROR "Undefined parameter '%s'" "$1"
     esac
     shift
 done
 
-[[ $# -lt 1 ]] && usage "Missing backup set name"
+(( $# < 1 )) && usage "Missing backup set name"
 opt_set="$1"; shift
 
 declare -A opts
-opts[log-file]=/var/log/rbashup.log
-opts[lock-file]=/var/run/rbashup.pid
-
-ini_read_section opts "$opt_config" global
-ini_read_section opts "$opt_config" "$opt_set"
+load_config
 
 now=$(date $date_format)
 
@@ -389,18 +414,14 @@ if ((lock_id > 0)) && ps -p "$lock_id" > /dev/null; then
 fi
 echo $$ > "${opts[lock-file]}"
 
-DEBUG "%s" "$(config_dump)"
-
 [[ -n $opt_n ]] && NOTICE "DRY RUN"
 
 # Do the backup
 
-dstbase="${opts[dst]}/$opt_set"
-dstfull="$dstbase/$now"
-latest="$dstbase/latest"
+dstfull="${opts[dst]}/$now"
+latest="${opts[dst]}/latest"
 
-[[ -z $opt_n ]] && mkdir -p "$dstbase"
-backup "${opts[src]}" "$dstbase" "$now" "${opts[excludes]}"
-purge "$dstbase" "$now"
+backup "${opts[src]}" "${opts[dst]}" "$now" "${opts[excludes]}"
+purge "${opts[dst]}" "$now"
 NOTICE "******* rbashup ended *******"
 rm "${opts[lock-file]}"
